apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "canary-checker.name" . }}-role
rules:
  - apiGroups:
      - canaries.flanksource.com
    resources:
      - canaries
      - systemtemplates
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - canaries.flanksource.com
    resources:
      - canaries/status
      - systemtemplates/status
    verbs:
      - get
      - patch
      - update
  # for creating and destroying pods during the pod canary test
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
      - services
    verbs:
      - "*"
  - apiGroups:
      - "metrics.k8s.io"
    resources:
      - pods
      - nodes
    verbs:
      - "*"
  # for getting the  XML results from junit tests
  - apiGroups:
      - ""
    resources:
      - pods/exec
      - pods/log
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - ingresses
    verbs:
      - "*"
  - apiGroups:
      - "extensions"
    resources:
      - ingresses
    verbs:
      - "*"
  # for reading configuration from canaries
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  # for leader election
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - configmaps/status
    verbs:
      - get
      - update
      - patch
